//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ADDROOM
    {
        public int id { get; set; }
        public string room_number { get; set; }
        public string room_type { get; set; }
        public string room_bed { get; set; }
        public string room_price { get; set; }
        public string room_book { get; set; }
    }
}
