//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EMPLOYEE
    {
        public int emid { get; set; }
        public string emname { get; set; }
        public string emphone { get; set; }
        public string emgender { get; set; }
        public string ememail { get; set; }
        public string emuser { get; set; }
        public string empassword { get; set; }
    }
}
