//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CHECKOUT
    {
        public int id_checkout { get; set; }
        public Nullable<System.DateTime> checkout { get; set; }
        public Nullable<int> id { get; set; }
    
        public virtual TBL_CHECKOUT TBL_CHECKOUT1 { get; set; }
        public virtual TBL_CHECKOUT TBL_CHECKOUT2 { get; set; }
    }
}
