//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_REGISTER
    {
        public int id { get; set; }
        public string cusname { get; set; }
        public string cusphone { get; set; }
        public string cusnational { get; set; }
        public string cusgender { get; set; }
        public Nullable<System.DateTime> cusdatebirth { get; set; }
        public string idProof { get; set; }
        public string cusaddress { get; set; }
        public Nullable<System.DateTime> cuscheckin { get; set; }
        public string roomnumber { get; set; }
        public string roombed { get; set; }
        public string roomtype { get; set; }
        public string roomprice { get; set; }
        public Nullable<System.DateTime> cuscheckout { get; set; }
    }
}
